name: Main Build

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['7.0' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Setup Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: dotnet restore QBic.sln
      - name: Build Solution
        run: dotnet build QBic.sln --configuration Release --no-restore
      - name: Create Nuget Package
        run: dotnet pack --no-build QBic.sln -c Release -o dist
      - name: Publish Nuget Package
        run: dotnet nuget push "dist\*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source ${{secrets.NUGET_SOURCE}} --skip-duplicate
